version: "2.1"

services:
  backend-db:
    build: ./backend/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3351:3306"
    volumes:
      - db_vol:/var/lib/mysql
    healthcheck:
      test: "exit 0"
  backend-api:
    build: ./backend/node
    volumes:
      - ./backend/node:/usr/src/app
    depends_on:
      backend-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

  frontend-app:
    tty: true
    build: ./frontend
    restart: always
    # working directory in container to place files
    working_dir: /usr/src/app
    # startup command if it takes a long time uncomment line 51 and comment line 50, if you do this 
    #   you must run `yarn` at the package.json level locally prior to starting
    command: bash -c "yarn && yarn start"
    # command: bash -c "yarn start"
    # map code volumes from local to inside working directory, changes made locally will update into the container
    volumes:
      - ./frontend:/usr/src/app
    # specify dependency on mysql db
    depends_on:
      - backend-api
    # ports to map, YOU CANNOT RUN ANYTHING ELSE ON PORT 3000
    ports:
      - 3000:3000
    # shared network
    networks:
      - frontend



# specify networks
networks:
  backend:
  frontend:

# persistent volume, comment all out if not using db_vol above
volumes:
  db_vol:
